// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGXbOGUKX4rDo6xcYETA74oa_YdnHOuNU',
    appId: '1:283326913020:web:d7129453864ffbbc59fa79',
    messagingSenderId: '283326913020',
    projectId: 'mazerunner-72b96',
    databaseURL: "https://mazerunner-72b96-default-rtdb.firebaseio.com/",
    authDomain: 'mazerunner-72b96.firebaseapp.com',
    storageBucket: 'mazerunner-72b96.appspot.com',
    measurementId: 'G-RWBNF20PVX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0lb_uA8PkHPgbAkc-X5C41GgKXu-a29s',
    appId: '1:283326913020:android:5bdc68d889723c0259fa79',
    messagingSenderId: '283326913020',
    databaseURL: "https://mazerunner-72b96-default-rtdb.firebaseio.com/",
    projectId: 'mazerunner-72b96',
    storageBucket: 'mazerunner-72b96.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOoPF2_3xbITJ2bYbokD_ut_fUIlLuZCs',
    appId: '1:283326913020:ios:e25ba4214b3f733359fa79',
    messagingSenderId: '283326913020',
    projectId: 'mazerunner-72b96',
    storageBucket: 'mazerunner-72b96.appspot.com',
    iosClientId: '283326913020-54s4laq37307ug5rohg3si229p23aem2.apps.googleusercontent.com',
    iosBundleId: 'com.example.mazeRunner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOoPF2_3xbITJ2bYbokD_ut_fUIlLuZCs',
    appId: '1:283326913020:ios:e25ba4214b3f733359fa79',
    messagingSenderId: '283326913020',
    projectId: 'mazerunner-72b96',
    storageBucket: 'mazerunner-72b96.appspot.com',
    iosClientId: '283326913020-54s4laq37307ug5rohg3si229p23aem2.apps.googleusercontent.com',
    iosBundleId: 'com.example.mazeRunner',
  );
}
